-- Question: Create a new database role named Analyst and grant this role SELECT access on the
-- Employee_View.
--G1_23BCS12396_Sagen_Session1

CREATE TABLE EMPLOYEE(
EMP_ID SERIAL PRIMARY KEY,
EMP_NAME VARCHAR(50),
EMP_SALARY DECIMAL(10,2)
);

INSERT INTO EMPLOYEE(EMP_NAME,EMP_SALARY) VALUES
('Sagen',51000),
('Arun',44000),
('Tarun',95000);

CREATE VIEW EMPLOYEE_VIEW
AS
SELECT * FROM EMPLOYEE;

CREATE ROLE Analyst
WITH LOGIN PASSWORD '1234';

GRANT SELECT ON EMPLOYEE_VIEW TO Analyst;
